# Generated by Django 4.2.2 on 2023-06-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completedTime',
            field=models.DateTimeField(null=True),
        ),
    ]
