# Generated by Django 4.2.2 on 2023-06-23 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_todofolders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
