# Generated by Django 4.2.2 on 2023-06-25 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alter_todo_options_alter_todofolders_folder_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todofolders',
            name='folder_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='todofolders',
            unique_together={('user', 'folder_title')},
        ),
    ]
