# Generated by Django 4.2.11 on 2024-04-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_rename_user_id_todo_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="todofolders",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
