# Generated by Django 5.0.4 on 2024-04-13 10:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_todo_until"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="todofolders",
            unique_together={("user", "folder_title"), ("user", "slug")},
        ),
    ]
