# Generated by Django 5.0.4 on 2024-04-18 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_todofolders_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="TodoCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "frequency_type",
                    models.CharField(
                        choices=[
                            ("daily", "DAILY"),
                            ("weekly", "WEEKLY"),
                            ("monthly", "MONTHLY"),
                        ],
                        max_length=20,
                    ),
                ),
                ("frequency", models.CharField(max_length=120, null=True)),
                ("end_date", models.DateField(null=True)),
                ("next_notification", models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name="todo",
            name="cycle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.todocycle",
            ),
        ),
    ]
