# Generated by Django 5.0.4 on 2024-04-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_todocycle_todo_cycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="todocycle",
            name="todo_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
