# Generated by Django 5.0.4 on 2024-04-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_todocycle_todo_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todocycle",
            name="todo_id",
            field=models.IntegerField(unique=True),
        ),
    ]
