# Generated by Django 5.0.4 on 2024-04-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_todocycle_todo_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todocycle",
            name="frequency",
            field=models.JSONField(max_length=120, null=True),
        ),
    ]
